### ISSUE TITLE
Cannot set Visibility or call Show, ShowDialog, or WindowInteropHelper.EnsureHandle after a Window has closed

### ISSUE THREAD

**Issue by Pekshev** [MahApps/MahApps.Metro#1964] opened 2015-06-09 16:32 UTC
Hi. I'm use windows with metro style in autocad's plugin. I catch this error, but a can't understand why it happen
Window's opening in autocad like this:
``` C#
public class MpTotalsFunction
    {
        // Вызов функции
        MpTotalsWindow _mpTotals;
        [CommandMethod("ModPlus", "mpTotals", CommandFlags.Modal)]
        public void Main()
        {
            if (_mpTotals == null)
            {
                _mpTotals = new MpTotalsWindow();
                _mpTotals.Closed += win_Closed;
            }

            if (_mpTotals.IsLoaded)
                _mpTotals.Activate();
            else
                AcApp.ShowModalWindow(AcApp.MainWindow.Handle, _mpTotals);
                //AcApp.ShowModelessWindow(AcApp.MainWindow.Handle, _mpTotals);
        }
        void win_Closed(object sender, EventArgs e)
        {
            _mpTotals = null;
            // Перевод фокуса
            Utils.SetFocusToDwgView();
        }
    }
```
In my window's code behinde i have this
``` C#
private void MpTotalsWindow_OnClosing(object sender, CancelEventArgs e)
        {
            if (_sheets.Count > 0 | _specifications.Count > 0 | _refDocs.Count > 0)
                if (string.IsNullOrEmpty(TbMainTotalFile.Text))
                    if (!MpQstWin.Show("Таблицы не сохранены в файл! После закрытия все данные будут потеряны!" +
                                       Environment.NewLine + "Вы уверены, что хотите закрыть окно?"))
                        e.Cancel = true;
        }

        private void MpTotalsWindow_OnClosed(object sender, EventArgs e)
        {
            SaveToSettingsFile();
            if (!string.IsNullOrEmpty(this.TbMainTotalFile.Text))
                SaveTotalsToFile(this.TbMainTotalFile.Text, false);
        }
```
Error occurs when i close window on this row:
``` C#
public void Update()
        {
            if (Owner.Visibility == Visibility.Hidden)
            {
                Visibility = Visibility.Hidden;

                UpdateCore();
            }
            else if (Owner.WindowState == WindowState.Normal)
            {
                if (this.closing) return;

error!       Visibility = IsGlowing ? Visibility.Visible : Visibility.Collapsed;
                glow.Visibility = IsGlowing ? Visibility.Visible : Visibility.Collapsed;

                UpdateCore();
            }
            else
            {
                Visibility = Visibility.Collapsed;
            }
        }
```
but the error does not always occur and I can not understand the reason

Sorry for my English - used online translator

**Comment by Pekshev** [comment] 2015-06-09 21:13
The problem in window owner. If open window like ``` _mpTotals.Show() ``` - no problem (but this method incorrect). If open like ``` AcApp.ShowModalWindow(AcApp.MainWindow.Handle, _mpTotals); ``` - sometimes has error

**Comment by punker76** [comment] 2015-06-11 09:41
@Pekshev is it possible to show us a complete stackstrace?

**Comment by Pekshev** [comment] 2015-06-11 16:04
That?
```
Приложение не поддерживает оперативную (JIT)
отладку. Подробная информацию приводится в конце данного сообщения.

************** Текст исключения **************
System.InvalidOperationException: Нельзя задать Visibility или вызвать Show, ShowDialog или WindowInteropHelper.EnsureHandle после закрытия окна.
   в System.Windows.Window.VerifyCanShow()
   в System.Windows.Window.CoerceVisibility(DependencyObject d, Object value)
   в System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   в System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   в System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   в System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   в MahApps.Metro.Controls.GlowWindow.Update()
   в MahApps.Metro.Controls.GlowWindow.<.ctor>b__12_26(Object sender, EventArgs e)
   в System.EventHandler.Invoke(Object sender, EventArgs e)
   в System.Windows.Window.OnActivated(EventArgs e)
   в System.Windows.Window.WmActivate(IntPtr wParam)
   в System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by gigios** [comment] 2015-10-01 08:15
I have the same exception (happen randomly).
In my case I have tried to use the reflection to check if the window is disposed in this way and seems working in a correct way.

        private bool IsDisposed
        {
            get
            {
                if (this.closing)
                    return true;

                var propertyInfo = typeof(Window).GetProperty("IsDisposed", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
                return (bool)propertyInfo.GetValue(this, null);
            }
        }

and in the Update method I have replaced the instruction:

if (this.closing) return;

with:

if (this.IsDisposed) return;

With this change seems working well.
I don't know if the usage of reflection is the best solution, but for the moment is the only solution found.

**Closed** 2016-06-09 14:06 UTC
Labels: Closing Until Further Notice

**Comment by szanto90balazs** [comment] 2016-07-05 08:08
I'm seeing crashes in our application due to the same exception as @Pekshev and @gigios were experiencing. Only problem is we couldn't reproduce it. There's a problem, which might be related. If a new window is opened and the user close it immediately, it crashes the application for sure, but it I couldn't debug it as it crashed the vshost process as well.

We're on `1.2.4.0`

#### Stack trace
```
 System.Windows.Window.VerifyCanShow():23
 System.Windows.Window.CoerceVisibility(DependencyObject d, Object value):15
 System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks):97
 System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType):645
 System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal):662
 System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value):14
 MahApps.Metro.Controls.GlowWindow.Update() in C:\Users\punker76\Documents\GitHub\MahApps.Metro\MahApps.Metro\Controls\GlowWindow.xaml.cs:256
 MahApps.Metro.Controls.GlowWindow.<.ctor>b__13_26(Object sender, EventArgs e) in C:\Users\punker76\Documents\GitHub\MahApps.Metro\MahApps.Metro\Controls\GlowWindow.xaml.cs:163
 System.EventHandler.Invoke(Object sender, EventArgs e):-1
 System.Windows.Window.OnActivated(EventArgs e):31
 System.Windows.Window.HandleActivate(Boolean windowActivated):27
 System.Windows.Window.WmActivate(IntPtr wParam):32
 System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled):198
 System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled):36
 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled):8
 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o):54
 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs):119
 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler):2
```

**Comment by lostmsu** [comment] 2017-07-21 06:09
In case you guys are still interested: I think this happens when graphics card driver is being updated.
