### ISSUE TITLE
Showing dialogs externally doesn't work? Always shows inside window

### ISSUE THREAD

**Issue by kennethVDL** [MahApps/MahApps.Metro#3729] opened 2020-01-25 15:10 UTC
Hey guys, I can't seem to get the ShowModalMessageExternal method from MetroWindow to actually show outside the application?

Even in the Demo (using the net47 version), when showing the different dialogs, they all show up inside the main window, EXCEPT for the customdialog; that one does show externally.

Screenshots:
![image](https://user-images.githubusercontent.com/14231754/73123157-fbc22f00-3f8c-11ea-9cfa-147373a0b170.png)
Becomes:
![image](https://user-images.githubusercontent.com/14231754/73123159-07155a80-3f8d-11ea-94ff-d3fe68032b15.png)

However,
![image](https://user-images.githubusercontent.com/14231754/73123163-0f6d9580-3f8d-11ea-8dba-dee41df398ff.png)
Becomes:
![image](https://user-images.githubusercontent.com/14231754/73123165-198f9400-3f8d-11ea-8017-6383d2d0bf30.png)

Is there something wrong with my configuration or is this a bug?

Thanks in advance!

Kind regards,
Kenneth

**Comment by kennethVDL** [comment] 2020-02-04 10:24
Hey everyone, it's been 10 days without any answer. It's the first time I commented on a GitHub page with an issue. If this is not how I should've flagged this to you, please show me what the usual path to take is.
Thanks.

**Comment by timunie** [comment] 2020-02-04 12:31
Hi @kennethVDL ,

sorry for the delay. I can confirm that there is a different behavior for `CustomDialog`. But I don't know which one is the intended one or where is the root cause. 

To your second question: It is always good to tell what is the current version you use. See also here: https://github.com/MahApps/MahApps.Metro/blob/develop/.github/CONTRIBUTING.md#bugs

*Please note: This is a free time project maintained by mainly one person (not me) at the moment. Due to this there may be a delay in the answer / fix. I really hope for your understanding*

Happy coding, Tim

**Comment by punker76** [comment] 2020-02-04 12:35
@kennethVDL I'm sorry nobody answered directly. Yes, I'm the maintainer of this project, but I have also a full time jib and a wonderful family...

Yes, the `ShowModal<XYZ>External` method works different to the `ShowDialogExternally` and `ShowModalDialogExternally` methods.

All of these creates a new Window for the Dialog and shows it up. Only the  `ShowModal<XYZ>External` method uses always the actual width of the owner (the main window).

So maybe, we can change this sometimes. Feel free to create a PR and we can discuss about this.

**Comment by kennethVDL** [comment] 2020-02-04 14:55
Hello @timunie and @punker76 , thanks for your replies! I honestly didn't try to sound rude and if I did, then I'd like to apologize. I'm just new to GitHub and was wondering if I maybe misunderstood how it worked! I appreciate your project and it has helped me immensely!

If I'm not mistaken I'm using version 1.6.5.

In any case, I thought the way it would work is that an external Dialog would show outside of the application (so using the actual width of the main screen) would make sense to me. And then the normal (non-external) dialogs would show inside the window that calls it.

 If that's not the intended design then I will have to look into making custom versions of those Dialogs.

Just to be sure, I will open a pull regarding my question, thank you! ( Should I close this after opening the PR?)

**Comment by kennethVDL** [comment] 2020-02-04 15:01
Apologies, it seems the pull request requires that I make the change to the code myself and then show you exactly what I changed by comparing my own branch to the main one.

I will have to look into this later :|

**Comment by timunie** [comment] 2020-02-04 15:02
@kennethVDL no in the PR you would reference this and close it there. Have a look at some existing PR to understand what I am talking about (e.g. https://github.com/MahApps/MahApps.Metro/pull/3527). 

Happy coding
Tim

**Comment by punker76** [comment] 2020-11-07 17:38
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏

**Closed by punker76** 2020-11-07 17:38 UTC
