### ISSUE TITLE
Simplified Chinese is not supported fully

### ISSUE THREAD

**Issue by incrediblink** [MahApps/MahApps.Metro#2033] opened 2015-07-13 14:58 UTC
When I text Simplified Chinese "确认登录", the word will be displayed wrongly.
What it should be:
![qq 20150713224753](https://cloud.githubusercontent.com/assets/7604366/8652479/77495ef6-29b1-11e5-9f76-872b4b77d458.png)
How it actually acts.
![qq 20150713224740](https://cloud.githubusercontent.com/assets/7604366/8652425/39574e28-29b1-11e5-861b-4f593364ad07.png)

In fact, it's a general problem for Windows 8 Apps. The point is that when it displays Simplified Chinese which is widely used in Mainland China, the program will first try it in Japanese. When the word doesn't exist in Japanese, it'll change to Traditional Chinese. And finally, it will change into Simplified Chinese. That's why the "确认登录" will display in different type of language.

Strangely, even when I wrote "FontFamily="微软雅黑"(a Simplified Chinese font)" in <Controls:MetroWindow>, this situation still happens.

**Comment by bigworld12** [comment] 2015-07-14 01:32
Well i am not a Chinese professional but they pretty much look the same for me except for the letter on the right which is a little bit different

**Comment by SkyZH** [comment] 2015-07-14 14:52
= = This bug is caused by Windows itself. The default font for windows 8 Metro Applications is Segoe UI and if you are using characters outside this font, windows will use another font. This method is called "Font fallback". In Windows 8, if you set the fallback in regedit correctly, unfortunately, windows will still not fallback to your selected font. In windows 10 this bug has been fixed with the help of some Chinese users reporting the bug.
Now you can set font to Microsoft Yahei UI to avoid this problem on Windows 8 or earlier.

**Closed** 2015-07-14 14:54 UTC

**Comment by quark-zju** [comment] 2015-09-26 13:00
@SkyZH Do you know more details about Windows 10 and fallback fonts? I see Chinese commas (`，`) display incorrectly after upgrading to Windows 10:

![comma](https://cloud.githubusercontent.com/assets/445459/10117659/20923eaa-6491-11e5-91de-870aad9ce556.png)

**Comment by SkyZH** [comment] 2015-09-26 13:21
Probably you need to specify the font as "Microsoft Yahei". Maybe this font is Meriyo, the default font of Japanese.

**Comment by quark-zju** [comment] 2015-09-26 13:37
It looks like "Microsoft JhengHei", which is the default UI font for traditional Chinese, or "Arial Unicode MS". These fonts should support Chinese comma anyway. The project (https://github.com/Epix37/Hearthstone-Deck-Tracker/) has more English users therefore it's probably not a good idea to hardcode a Chinese font.

I'd like to find a way that only modifies system settings (the registry) to let Windows fallback ` ， ` from Segoe UI correctly. Sadly I do not know where to start and how to debug. `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink` has defined "Segoe UI" fallbacks to "Microsoft YaHei UI" correctly.

**Comment by SkyZH** [comment] 2015-09-26 13:42
Sometime the font callback defined in Font Link doesn't make sense. Also you may restart your computer to see if Font Link is actually modified successfully.

**Comment by SkyZH** [comment] 2015-09-26 13:45
The best way is to use tools such as MacType to change the default behavior of rendering font. With MacType, you can easily alias Segoe UI as Microsoft Yahei.
Some Fonts you may need to change:
Microsoft JhengHei
Arial
Segoe UI
Meiryo

**Comment by quark-zju** [comment] 2015-09-26 14:00
I just found it's a Windows issue not related to MahApps.Metro. Visual Studio appearly has the same issue if Windows display language is English.

![vscomma](https://cloud.githubusercontent.com/assets/445459/10117876/336b9b9a-6499-11e5-9165-3405297facb7.png)

I will try to find a decent solution elsewhere. MacType may destabilize the system. It's a risk I'd like to avoid.

**Comment by quark-zju** [comment] 2015-09-26 15:18
It seems replacing all "Segoe UI" to "Microsoft YaHei UI" in  [HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics] solves my problem.
