### ISSUE TITLE
Win + Shift + Left/Right does not work in multimonitor setup with more than 2 monitors

### ISSUE THREAD

**Issue by pfattisc** [MahApps/MahApps.Metro#2388] opened 2016-03-02 14:22 UTC
## What steps will reproduce this issue?

In a multimonitor setup with 3 monitors _win+shift+left/right_ moves the current metrowindow to the next (defined by left resp. right arrow key) monitor. Trying to move the window back to the primary monitor with _win+shift+left/right_ fails.
This issue is only present when the metrowindow is maximized.
### Expected outcome

_win+shift+left/right_ should move the metrowindow from one monitor to another monitor regardless if it is maximized or not.
### Environment
- MahApps.Metro **v1.2.4**
- Windows **7 x64**
- Visual Studio **2013**
- .NET Framework **4.5**

**Comment by punker76** [comment] 2016-03-02 14:46
@pfattisc Any other special on your Window? I can't reproduce this with the MahApps main demo on my 2 monitor setup with win 7. Do you also tested it with the latest source (pre-release) and the main demo?

**Comment by punker76** [comment] 2016-03-02 14:55
@pfattisc Ok, tested on a 3 monitor station with latest source and all works fine... [Here](https://github.com/punker76/MaximizedMetroWindowTest) is my working sample.

**Comment by pfattisc** [comment] 2016-03-02 15:28
Thx @punker76.
Tried your demo and still have the issue.
Not sure what it depends on but one difference is that I have .NET 4.5 installed and your demo asks for .NET 4.5.2.
Attached pics  of my monitor configuration
![multimonitor_2](https://cloud.githubusercontent.com/assets/11867529/13464774/fe4ddf4c-e092-11e5-9280-cc00be6a0944.png)
![multimonitor_3](https://cloud.githubusercontent.com/assets/11867529/13464775/fe4f1a6a-e092-11e5-8f34-5325f3a7ad3e.png)
![multimonitor_1](https://cloud.githubusercontent.com/assets/11867529/13464773/fe4dca70-e092-11e5-8ee3-96e7de76d003.png)

**Comment by punker76** [comment] 2016-03-02 15:47
@pfattisc You are using classic design?  Can you try this with Aero (glass enabled) design?

**Comment by pfattisc** [comment] 2016-03-02 15:52
@punker76 switched to Aero but it still remains...
Have you tested it with window in maximized state?

**Comment by punker76** [comment] 2016-03-02 15:53
@pfattisc my sample starts in maximized state and works on my machines™

**Comment by amoamare** [comment] 2016-04-21 15:28
This is working as intended on my setup with windows 10, later I will test windows 7 machine.
Across 2,3,6 monitors fine. Although windows 10 has snap features but it's working as intended.

**Comment by punker76** [comment] 2016-09-20 21:36
@pfattisc Please, another test, try the latest pre-release... :-D

**Comment by pfattisc** [comment] 2016-09-21 08:35
@punker76 Ok, I did another test with your working sample and the latest pre-release but the problem still persists...

**Comment by punker76** [comment] 2016-10-28 22:34
@pfattisc I tested this on different machines with different multi monitors and all works... I don't really know what's going wrong at your hardware setup :-(

**Comment by pfattisc** [comment] 2016-11-04 11:02
@punker76 never mind, this is no showstopper at all, plus this might have various reasons despite from MahApps. In a few days the hardware is changed (and new OS) so maybe this will fix it...

**Comment by pfattisc** [comment] 2016-11-04 11:02
@punker76 never mind, this is no showstopper at all, plus this might have various reasons despite from MahApps. In a few days the hardware is changed (and new OS) so maybe this will fix it...

**Comment by punker76** [comment] 2016-11-04 12:34
@pfattisc I close this for now. Open it again if it's then still an issue... thx.

**Closed by punker76** 2016-11-04 12:34 UTC
