### ISSUE TITLE
Cannot fully programatically maximize window.

### ISSUE THREAD

**Issue by pingu2k4** [MahApps/MahApps.Metro#1823] opened 2015-02-27 13:25 UTC
Hi,

Having this live of code called: `this.WindowState = System.Windows.WindowState.Maximized;`

does change the size of the window, however there are borders all around the window, where the window isn't touching the edge of the screen or the taskbar. Here is my opening window tag:

```xaml
    <Controls:MetroWindow x:Name="GameWindow" x:Class="WpfApplication1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
                      ShowMinButton="False"
                      ShowMaxRestoreButton="False"
                      ResizeMode="NoResize"
                      SaveWindowPosition="True"
        Title="MainWindow" Height="350" Width="525" GlowBrush="#FF07908E" Background="#FF252525"
                      WindowState="Maximized"
                      IgnoreTaskbarOnMaximize="True">
```

Effectively, I want to come out of fullscreen as it is set to when it launches, and have it take up all the screen but not cover the taskbar... Which it does apart from it leaves this strange gap around....

![2](https://cloud.githubusercontent.com/assets/11229848/6413129/0cafba74-be84-11e4-9e34-701d18d22732.jpg)

**Comment by punker76** [comment] 2015-02-27 13:33
@pingu2k4 which version?

**Comment by pingu2k4** [comment] 2015-02-27 13:35
Apologies. Version 1.1.1.0.

As can probably be seen by the simplicity of the program so far I am kind of new to this framework, but I can't find how to do this anywhere I search online, and I'm sure that it should work correctly with what I have...

**Comment by pingu2k4** [comment] 2015-02-27 18:40
Just an update - I am now at home where I have 2 monitors and not just 1.
I get the exact same result here with the same project. however, I created a new project with mahapps.metro and a simple button. I used the same line of code to maximise, and on the new project it worked fine...

**Comment by pingu2k4** [comment] 2015-02-27 21:51
OK, so I have found out where the problem lies. I had set
    ResizeMode="NoResize"
And this is where the problem lies. I don't know whether it is expected behaviour to act as it does when this is set to noresize, but I can get this working properly with the following:

    this.ResizeMode = System.Windows.ResizeMode.CanResize;
    this.IgnoreTaskbarOnMaximize = !this.IgnoreTaskbarOnMaximize;
    this.WindowState = System.Windows.WindowState.Maximized;
    this.ResizeMode = System.Windows.ResizeMode.NoResize;
I am happy with using this whether I should have to or not really... I'll just keep this open for time being in case you want to do anything with this still. :) Feel free to close though.

**Comment by punker76** [comment] 2015-02-27 21:54
@pingu2k4 this is fixed with 39a7e05a512f21d6f3fa55ec363665b3429b021f

**Comment by davidefu** [comment] 2016-03-18 13:51
hi everyone, 
i think this issue is still open in version 1.2.4 (from nuget).
please check the attached project
thanks
Davide
[mahappsdemo.zip](https://github.com/MahApps/MahApps.Metro/files/179731/mahappsdemo.zip)

**Comment by punker76** [comment] 2016-03-25 21:45
@davidefu Should be fixed now in latest pre-release. As a workaround (with latest stable 1.2.4) set the ResizeMode in loaded event 

```csharp
this.Loaded += (sender, args) => this.ResizeMode = ResizeMode.NoResize;
```

**Closed by punker76** 2016-03-25 21:45 UTC
Labels: Bug, in progress

**Comment by davidefu** [comment] 2016-03-26 08:15
thanks

**Comment by davidefu** [comment] 2016-04-20 16:37
hi,
strange issue in the last alpha version 1.3.0.134
if i create a window with style: none, resizemode: noresize, state: Maximized the window ignore the window taskbar and overlap.
but there is a way to resize the window with the shortcut windows + down arrow
if i force in the windowstatechanged event the maximized state, the window is not fully maximized.

By the way wich is the correct way to create a full (with no taskbar overlapping) non resizable window?
please check the attached project

![immagine](https://cloud.githubusercontent.com/assets/17928925/14682614/b93bf122-0726-11e6-8c4d-7bac4e2fc546.png)
[mahappsalphaissue.zip](https://github.com/MahApps/MahApps.Metro/files/228367/mahappsalphaissue.zip)

Thanks

**Comment by punker76** [comment] 2016-04-25 18:54
@davidefu Is this a normal running Win10? or is it inside a VM?

You can use `IsWindowDraggable="False"` instead doing this

```csharp
        void MainWindow_StateChanged(object sender, EventArgs e)
        {
            if (this.WindowState != System.Windows.WindowState.Maximized)
            {
                this.WindowState = System.Windows.WindowState.Maximized;
            }
        }
```

Here is the working xaml (without any code behind stuff) that works here on my win 7 prof 64 bit machine

```xaml
<Controls:MetroWindow x:Class="WpfApplication2.MainWindow"
                      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                      xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
                      Title="MainWindow"
                      Width="525"
                      Height="350"
                      ResizeMode="NoResize"
                      IsMinButtonEnabled="False"
                      IsWindowDraggable="False"
                      Topmost="True"
                      WindowState="Maximized"
                      WindowStyle="None">
  <Grid Background="Red">
    <TextBlock><Run Text="1.3.0.134" /></TextBlock>
  </Grid>
</Controls:MetroWindow>
```

**Comment by punker76** [comment] 2016-04-25 19:04
@davidefu by the way, the shortcut windows + down arrow is normal behavior in win 10, just tested it out with normal window instead MetroWindow.

And, I take your sample with my changes and run it inside VMWare with Win10... and it works :-(

![2016-04-25_21h03_06](https://cloud.githubusercontent.com/assets/658431/14795523/2b13639c-0b29-11e6-88c6-fa6891cfd142.png)

![2016-04-25_21h03_22](https://cloud.githubusercontent.com/assets/658431/14795524/31e8740a-0b29-11e6-975a-8d0aea2f941c.png)

**Comment by davidefu** [comment] 2016-04-26 07:52
hi,
i'm on a normal windows 10 on a surface pro 4 (so with 175% or 200% of zoom)
i tried with your code, but i don't understand how to make the window maximized without overlap the taskbar.
so is there a way to override the behavior of the windows + down arrow?
if i force (with the code you saw on statechanged event) the maximized state the window appears with the border around it.
same issue if i set the maximized state on windows loaded insted of one the xaml

thanks
davide

**Comment by punker76** [comment] 2016-04-26 09:01
>i'm on a normal windows 10 on a surface pro 4 (so with 175% or 200% of zoom)

ok, i'll try on my VM and PC this setting with Win 10, but not with a surface, that's not my price class :-)

>i tried with your code, but i don't understand how to make the window maximized without overlap the taskbar.

taskbar issue is (should be) fixed with MahApps.Metro 1.3.0-ALPHA137

>so is there a way to override the behavior of the windows + down arrow?

i don't know, maybe you can prevent the keys in preview key events

>if i force (with the code you saw on statechanged event) the maximized state the window appears with the border around it.

setting the maximized state in the state event is not a good idea

>same issue if i set the maximized state on windows loaded insted of one the xaml

yeah maybe this is an issue with your settings of the dpi zoom...

**Comment by davidefu** [comment] 2016-04-26 10:16
great. l'll be happy to test the next release

**Comment by punker76** [comment] 2016-04-26 10:30
@davidefu by the way `ResizeMode="NoResize"` and `WindowState="Maximized"` are not good friends! doesn't working with normal windows too!

**Comment by davidefu** [comment] 2016-04-26 15:28
@punker76 now in the alpha 137 resizemode="NoResize" and WindowState="Maximized" seems to be good friends also with high dpi monitor. Thanks a lot for the support.
Extra chapter:
with this code i was able to override the windows + down arrow

`private const int WM_SYSCOMMAND = 0x0112;
        private const int SC_RESTORE = 0xF120;

        protected override void OnSourceInitialized(EventArgs e)
        {
            base.OnSourceInitialized(e);
            HwndSource source = PresentationSource.FromVisual(this) as HwndSource;
            source.AddHook(WndProc);
        }

        private IntPtr WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
        {
            if (msg == WM_SYSCOMMAND && wParam.ToInt32() == SC_RESTORE)
            {
                Debug.WriteLine(msg);
                handled = true;
            }

            return IntPtr.Zero;
        }`

extra detail here https://msdn.microsoft.com/en-us/library/windows/desktop/ms646360(v=vs.85).aspx

**Comment by davidefu** [comment] 2016-05-04 13:36
@punker76 
hi, i've found another really strange issue.
it's happening only with a .NET 4.0 apps (not in .NET 4.5)
and it's not reproducible with the visual studio debugger attacched, so only running from the bin folder directly
you can see that the window is not fully maximized
![image](https://cloud.githubusercontent.com/assets/17928925/15015577/0d0cacce-120d-11e6-91ef-e765ea52d57d.png)
i've tested it on windows 10 with 100% of zoom and 175% of zoom, save behavior
please find the attacched project
[WpfApplication2.zip](https://github.com/MahApps/MahApps.Metro/files/248805/WpfApplication2.zip)

**Comment by davidefu** [comment] 2016-05-04 14:47
can be that a possible related issue? http://stackoverflow.com/questions/19280016/windowchrome-resizeborderthickness-issue

**Comment by punker76** [comment] 2016-05-04 15:29
@davidefu please try again with 1.3.0.145, thx!!!

**Comment by punker76** [comment] 2016-05-04 20:43
@davidefu any news?

**Comment by davidefu** [comment] 2016-05-04 20:47
@punker76 hi, the test app attacched is working fine.
tomorrow morning i'll make a more deep test and on a different machine.

**Comment by davidefu** [comment] 2016-05-05 07:10
i notice a strange issue.
with noresize in xaml i can still resize with win+arrow
this is not possible if i set noresize in loaded event but the window overlap the taskbar

**Comment by punker76** [comment] 2016-05-05 07:23
I think we can't fix this in a good way, NoResize and maximized window is
always a bad combination ( also without MahApps ). And I don't get your
issue with the overlapping taskbar. resizing with win+arrow should be
possible, so the window can be moved to another monitors without the sizing
bug.
Am 05.05.2016 9:10 vorm. schrieb "davidefu" <notifications@github.com>:

**Comment by davidefu** [comment] 2016-05-05 07:48
the win+arrow was not possible in previous alpha

the window overlap the taskbar only if i the the resize mode in loaded event and nothing in the xaml

**Comment by davidefu** [comment] 2016-05-05 07:52
the alpha141 has good bahavior except for the runtime issue regarding the borderthickness

**Comment by davidefu** [comment] 2016-05-05 12:10
maybe a typo but in BorderlessWindowBehavior.cs at line 84
if you change the line to this.AssociatedObject.ResizeMode = ResizeMode.NoResize;
the behavior seems to be correct
