### ISSUE TITLE
Validation popup only shows once when errors cleared & readded

### ISSUE THREAD

**Issue by didster** [MahApps/MahApps.Metro#3809] opened 2020-05-23 09:02 UTC
**Describe the bug**
I am unsure if this is intentional behaviour, but its defiantly different from previous versions both alpha and non-alpha.  When a validation error is fired for a control the validation tool tip appears (expected).  If the error is cleared, it disappears (expected).  If however the control generates another error, the tool tip is not shown - only the red highlight is shown (hovering over the triangle also does not show the error)  

**To Reproduce**

- Using the demo app go to text tab, enter 2 in the number smaller than 10 control (it defaults to 2).  Error correctly shows
![Step_1](https://user-images.githubusercontent.com/6229977/82726413-d4c9fe80-9cdb-11ea-917b-8806547cfda2.png)

- Change value to 20, error disappears:
![Step_2](https://user-images.githubusercontent.com/6229977/82726412-d4c9fe80-9cdb-11ea-8c7f-987675c27144.png)

- Change value back to 2 (or any other value less than 10).  Tool tip does not show.  Previous versions did.
![Step_3](https://user-images.githubusercontent.com/6229977/82726410-d4316800-9cdb-11ea-8787-aae893a39174.png)

**Expected behavior**
I would expect the error to re-show each time since if you are conveying information in the error like "must enter 5 digits" and so forth the user may not remember the content from the first error.

**Screenshots**

**Environment(please complete the following information):**
- MahApps.Metro version [2.0.0-alpha0879]
- OS: Win10 18362
- Visual Studio 2019 (16.5.2)
- .NET Framework: Core 3.1

**Comment by didster** [comment] 2020-05-23 09:08
Actually just noticed, the error does briefly flash up - way outside the window bounds.  A screen shot is difficult but hopefully this is clear

![Screenshot_143](https://user-images.githubusercontent.com/6229977/82726614-540c0200-9cdd-11ea-8f44-2e0e3135bfbd.png)

**Comment by punker76** [comment] 2020-05-23 09:41
@didster I think this was fixed with #3804 because I can not reproduce this with the latest source. You can test this with 2.0.0-alpha0886

**Closed by punker76** 2020-05-23 09:41 UTC
Labels: Bug

**Comment by didster** [comment] 2020-05-23 14:19
@punker76 Perfect thanks, indeed all is fine again now with alpha0888
