### ISSUE TITLE
Program Freeze if ManualResetEvent is passed into new thread

### ISSUE THREAD

**Issue by Ksdmg** [MahApps/MahApps.Metro#3907] opened 2020-08-19 15:17 UTC
## Describe the bug

When you show a window in a new thread and surround the call with a ManualResetEvent, the window never opens.

## Steps to reproduce

I have prepared a sample application here: [MahAppsMetroResetEvent](https://github.com/Ksdmg/MahAppsMetroResetEvent)

I have a main WPF window that creates a window in a new thread. Just click the button in the sample app.

As soon as you comment out the section `Using ready As New ManualResetEvent(False)` in file Box.Box the window is shown. So I guess it must have to do something with the reset event.

## Expected behavior

I would expect that a new window in a new thread is being created.

## Actual behavior

The application freezes and the new window is never shown.

## Environment

MahApps.Metro version: v2.2.0
Windows build number: Win10 1809
Visual Studio: 2019 16.7.2
Target Framework: v4.8

**Comment by punker76** [comment] 2020-08-19 15:35
@Ksdmg The ShowDialog method of a window opens the window modal, so you should change the order of  these to lines

```
                                           Box.ShowDialog()
                                           ready.Set()
```

to 

```
                                           ready.Set()
                                           Box.ShowDialog()
```

**Comment by Ksdmg** [comment] 2020-08-19 16:17
@punker76 thanks for the fast answer.
I need the order like this to pause the main thread until the newly dialog has been closed. If you remove all MahApps.Metro references from the child window and make it a normal window it shows up just fine.

**Comment by punker76** [comment] 2020-11-28 18:35
@Ksdmg I tried again your test sample together with the latest v2.3.4 and it seems the issue is gone. I will close this for now. If you still have trouble with this then reopen this one. Thx

**Closed by punker76** 2020-11-28 18:35 UTC
Labels: Bug
