### ISSUE TITLE
Window maximizing doesn't work when AllowsTransparency set to true

### ISSUE THREAD

**Issue by RayMeOut** [MahApps/MahApps.Metro#2483] opened 2016-04-24 16:59 UTC
I have experienced a bit a weird behavior of the MahApps Window when I set the `AllowsTransparency` to true. What I am doing is to set the Opacity of the whole window to 0.4 when the mouse leaves the window. When the mouse returns to the window area, the opacity is set back to a value of 1.0.

This works fine unless I want to maximize the MahApps window. It doesn't maximize, but makes a weird blue rectangle around half of the screen, and the window remains the same size as before (The window is resizable... and without the `AllowsTransparency`(in code, after `InitializeComponent`) everything works fine).

See a short clip on [giphy](https://media.giphy.com/media/3o6ozjqTOd33pcBzIk/giphy.gif)
## What steps will reproduce this issue?

When I start the application and maximize the window immediately, the window changes it's position to (0,0) but doesn't resize to full size (screen size). It just remains the same size as before.
If I pull the window to the right or the left side of the screen (like WIN+Left/Right) first, and then try to maximize, I get the result visible in the clip above.

This only happens, when I set `AllowsTransparency` in code after initializing. When I set it in the xaml, the window does not use transparency but a semi-black overlay.

I there any way to get this working? If more information are needed, just ask ;)

Thank you in advance.
RayMeOut
## 
### Environment
- MahApps.Metro **v1.2.4**
- Windows **8.1**
- Visual Studio **2013 Professional**
- .NET Framework **4.5**

PS: I've already asked this question ([link](http://stackoverflow.com/questions/36823374/mahapps-window-maximizing-doesnt-work-when-allowstransparency-set-to-true)), but I thought, I belongs to this site.

**Comment by punker76** [comment] 2016-04-25 08:20
@RayMeOut I tested this out with the latest source and can't reproduce this. So, please take the latest pre-release via NuGet, maybe this is fixed for you, thx!

![2016-04-25 10h17_21](https://cloud.githubusercontent.com/assets/658431/14777728/3e05ef92-0acf-11e6-9081-8bf12fa5a56c.gif)

**Comment by RayMeOut** [comment] 2016-04-25 15:31
Hey @punker76 
Thank you for your response. I've tried your suggestion and installed 1.3.0-ALPHA (136), but the behavior is still there... :/ I've also tried a new project but the result was the same.
But this miss-displaying only appears when i try to maximize the window, not when only using half of the screen (Did you try that as well to reproduce?).
And the new project i created only contains this `AllowsTransparency `set to True and nothing else. So it shouldn't be affected by other parts of the code :/

**Comment by punker76** [comment] 2016-04-25 18:37
@RayMeOut Is you Win 8.1 running inside a VM? or normal PC? Do you have a chance to test it on a different os?

**Comment by RayMeOut** [comment] 2016-04-25 20:47
@Punker76 My Win is running normal on a pc (not inside a vm). I've startet the .exe on another computer  (but also Win 8.1) and there was the same "error"

**Comment by punker76** [comment] 2016-04-25 21:05
@RayMeOut ok, thx. seems like a Win8.1 issue :-(

**Comment by RayMeOut** [comment] 2016-04-26 09:37
@Punker76 ok, I will try this on a Win10 pc, but I need to wait until this evening, because I cannot access my code at my workplace. And neither I have VS.

**Comment by RayMeOut** [comment] 2016-04-26 16:56
Hey @Punker76, I tried the application on another PC with Win10 running and it was working without problems. You were right, it is at least a Win8.1 issue... :/ (But only with MahApps, a "normal" app with the default window was working normal) :/ Would it be possible to get this working in the (near) future (next releases)? Would be glad to use this feature also on Win8.1... :) Thanks and regards
RayMeOut

**Comment by NickHarmer** [comment] 2016-09-26 13:40
Has there been any further movement on this issue?  I've had to a code huge number of window-subclassing workarounds to make this work as it should, and every time Micro$oft release an update it breaks and I have to rewrite it!

It is definitely **NOT** just a windows 8/8.1 problem - it occurs on machines running Windows 10 (original and anniversary) as well.  I have just built a new test project based off MahApps 1.3.0 and the bug is still present, even with no other code except **AllowTransparency=true** after the InitializeComponent() call.

The issue does **NOT** occur when using Aero Snap to pin a window to the left-hand or right-hand side, but **DOES** occur when dragging a window to the top of the screen, or when using the maximize button or menu item, or when maximizing programmatically in code-behind.  It also occurs on both single and multi-monitor systems (all screens).

Is there any likelihood that this issue will be fixed in 1.4.0, or is it already fixed in a 1.3 alpha which I could test against?

**Comment by RayMeOut** [comment] 2016-09-27 17:52
I've just tested my code with the newest alpha (1.4.0) and still get the same behavior.
But I'm "glad" to hear, that I'm not the only one with this problem

I avoided this problem by not using `AllowTransparency` (that's the reason, that I do not have further information to this topic)... But I know that this is not a solution and I really wanted to use this feature

**Comment by punker76** [comment] 2016-09-27 18:14
@RayMeOut @NickHarmer 

MahApps sets the `AllowTransparency` property is to false, cause true has some nasty bugs, e.g. like your issue.

It breaks also the TextBox ClearType and sometimes UI Performance is bad.

-> https://github.com/MahApps/MahApps.Metro/pull/1537
-> https://github.com/MahApps/MahApps.Metro/issues/1536

**Closed** 2017-10-07 23:57 UTC
