### ISSUE TITLE
Title bar is not collapsed when set ShowTitlebar=False on Latest Release 1.6.0

### ISSUE THREAD

**Issue by HuKyle99** [MahApps/MahApps.Metro#3200] opened 2018-03-06 03:02 UTC
When I setup the WPF MetroWindow, the Title bar is not collapsed when set ShowTitlebar=False on Latest Release 1.6.0
But is works on release 1.6.0-alpha0184

Here is the result of test window, release 1.6.0
![1 6 0](https://user-images.githubusercontent.com/29476900/37011990-6f182106-212d-11e8-8aa4-cc6b37905a9f.jpg)

Here is the result of test window, release 1.6.0-alpha0184
![1 6 0_alpha0184](https://user-images.githubusercontent.com/29476900/37011993-72d0ed00-212d-11e8-9303-ac17127cdbcb.jpg)

**Comment by bbougot** [comment] 2018-03-08 09:50
Seems linked to https://github.com/MahApps/MahApps.Metro/issues/3192
@punker76 Any ETA for a fix?

**Comment by alovegit** [comment] 2018-03-13 13:31
Not ideal, but as a workaround you can set TitlebarHeight="0".

**Comment by punker76** [comment] 2018-03-19 07:37
Duplicate of #3192

**Closed by punker76** 2018-03-19 07:37 UTC
Labels: Duplicate
