### ISSUE TITLE
Detected package version outside of dependency constraint: MahApps.Metro 2.4.10 requires ControlzEx (>= 4.4.0 && < 6.0.0) but version ControlzEx 6.0.0 was resolved.

### ISSUE THREAD

**Issue by EmilNachev** [MahApps/MahApps.Metro#4465] opened 2024-02-15 19:29 UTC
Detected package version outside of dependency constraint: MahApps.Metro 2.4.10 requires ControlzEx (>= 4.4.0 && < 6.0.0) but version ControlzEx 6.0.0 was resolved.

**Comment by timunie** [comment] 2024-02-16 07:14
ControlEx 6 will only be supported in 3.0 or in current nightly. That is by design and not a bug. Either downgrade as well or use nightly for now.

**Comment by natnawatt** [comment] 2024-02-29 16:33
> Detected package version outside of dependency constraint: MahApps.Metro 2.4.10 requires ControlzEx (>= 4.4.0 && < 6.0.0) but version ControlzEx 6.0.0 was resolved.

1NNAP4ZYwn63KHZXG5vPaP26W3ixdFSw4510:49:06 AM: Build ready to start
10:49:19 AM: build-image version: fcb0c1b3ada6d25c1cb58e8bc514f5f23cc14f15 (focal)
10:49:19 AM: buildbot version: 742cd4f739071a396139ba5020a96a927941b57d
10:49:19 AM: Fetching cached dependencies
10:49:19 AM: Failed to fetch cache, continuing with build
10:49:19 AM: Starting to prepare the repo for build
10:49:19 AM: No cached dependencies found. Cloning fresh repo
10:49:19 AM: git clone --filter=blob:none https://github.com/w3c/wai-intro-wcag
10:49:19 AM: Preparing Git Reference pull/275/head
10:49:21 AM: Custom build command detected. Proceeding with the specified command: "git submodule update --init --remote && bundle exec jekyll build --config "_config.yml,_config_staging.yml""
10:49:21 AM: Starting to install dependencies
10:49:21 AM: Python version set to 3.8
10:49:21 AM: Attempting Ruby version 2.6.2, read from environment
10:49:22 AM: Required ruby-2.6.2 is not installed - installing.
10:49:22 AM: Searching for binary rubies, this might take some time.
10:49:22 AM: Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/20.04/x86_64/ruby-2.6.2.tar.bz2
10:49:22 AM: Checking requirements for ubuntu.
10:49:22 AM: Requirements installation successful.
10:49:23 AM: ruby-2.6.2 - #configure
10:49:23 AM: ruby-2.6.2 - #download
10:49:23 AM: ruby-2.6.2 - #validate archive
10:49:26 AM: ruby-2.6.2 - #extract
10:49:28 AM: ruby-2.6.2 - #validate binary
10:49:28 AM: ruby-2.6.2 - #setup
10:49:28 AM: ruby-2.6.2 - #gemset created /opt/buildhome/.rvm/gems/ruby-2.6.2@global
10:49:28 AM: ruby-2.6.2 - #importing gemset /opt/buildhome/.rvm/gemsets/global.gems........................................
10:49:29 AM: ruby-2.6.2 - #generating global wrappers........
10:49:29 AM: ruby-2.6.2 - #gemset created /opt/buildhome/.rvm/gems/ruby-2.6.2
10:49:29 AM: ruby-2.6.2 - #importing gemsetfile /opt/buildhome/.rvm/gemsets/default.gems evaluated to empty gem list
10:49:29 AM: ruby-2.6.2 - #generating default wrappers........
10:49:29 AM: Using /opt/buildhome/.rvm/gems/ruby-2.6.2
10:49:30 AM: Using Ruby version 2.6.2
10:49:30 AM: Using Bundler version 2.3.10 from Gemfile.lock
10:49:43 AM: Successfully installed bundler-2.3.10
10:49:43 AM: 1 gem installed
10:49:43 AM: Started restoring cached ruby gems
10:49:43 AM: Finished restoring cached ruby gems
10:49:43 AM: Installing gem bundle
10:49:43 AM: [DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path "/opt/build/cache/bundle"`, and stop using this flag
10:49:43 AM: [DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs --all`
10:49:44 AM: Resolving dependencies...Fetching gem metadata from https://rubygems.org/...........
10:49:44 AM: ..................................
10:49:44 AM: Using bundler 2.3.10
10:49:44 AM: Fetching eventmachine 1.2.7
10:49:44 AM: Fetching faraday-net_http 3.0.1
10:49:44 AM: Fetching ruby2_keywords 0.0.5
10:49:44 AM: Fetching ffi 1.15.5
10:49:44 AM: Fetching liquid 4.0.3
10:49:44 AM: Fetching mercenary 0.4.0
10:49:44 AM: Fetching safe_yaml 1.0.5
10:49:44 AM: Fetching unicode-display_width 2.3.0
10:49:44 AM: Fetching jekyll-paginate 1.1.0
10:49:44 AM: Fetching rubyzip 2.3.2
10:49:44 AM: Fetching public_suffix 5.0.0
10:49:44 AM: Fetching colorator 1.1.0
10:49:44 AM: Fetching concurrent-ruby 1.1.10
10:49:44 AM: Fetching http_parser.rb 0.8.0
10:49:44 AM: Fetching rb-fsevent 0.11.2
10:49:44 AM: Fetching rexml 3.2.5
10:49:44 AM: Fetching rouge 3.30.0
10:49:44 AM: Fetching webrick 1.7.0
10:49:44 AM: Fetching forwardable-extended 2.6.0
10:49:44 AM: Installing jekyll-paginate 1.1.0
10:49:44 AM: Installing ruby2_keywords 0.0.5
10:49:44 AM: Installing mercenary 0.4.0
10:49:44 AM: Installing faraday-net_http 3.0.1
10:49:44 AM: Installing unicode-display_width 2.3.0
10:49:44 AM: Installing safe_yaml 1.0.5
10:49:44 AM: Installing colorator 1.1.0
10:49:44 AM: Installing rubyzip 2.3.2
10:49:44 AM: Installing webrick 1.7.0
10:49:44 AM: Installing forwardable-extended 2.6.0
10:49:44 AM: Installing rb-fsevent 0.11.2
10:49:45 AM: Installing liquid 4.0.3
10:49:45 AM: Installing rexml 3.2.5
10:49:45 AM: Installing public_suffix 5.0.0
10:49:45 AM: Installing http_parser.rb 0.8.0 with native extensions
10:49:45 AM: Installing eventmachine 1.2.7 with native extensions
10:49:45 AM: Installing concurrent-ruby 1.1.10
10:49:45 AM: Fetching pathutil 0.16.2
10:49:45 AM: Fetching faraday 2.6.0
10:49:45 AM: Installing rouge 3.30.0
10:49:45 AM: Installing pathutil 0.16.2
10:49:45 AM: Fetching terminal-table 3.0.2
10:49:45 AM: Installing faraday 2.6.0
10:49:45 AM: Installing terminal-table 3.0.2
10:49:45 AM: Installing ffi 1.15.5 with native extensions
10:49:45 AM: Fetching addressable 2.8.1
10:49:45 AM: Installing addressable 2.8.1
10:49:45 AM: Fetching kramdown 2.4.0
10:49:45 AM: Installing kramdown 2.4.0
10:49:45 AM: Fetching sawyer 0.9.2
10:49:45 AM: Installing sawyer 0.9.2
10:49:45 AM: Fetching octokit 4.25.1
10:49:45 AM: Installing octokit 4.25.1
10:49:58 AM: Fetching i18n 1.12.0
10:49:58 AM: Installing i18n 1.12.0
10:50:03 AM: Fetching kramdown-parser-gfm 1.1.0
10:50:03 AM: Installing kramdown-parser-gfm 1.1.0
10:50:03 AM: Fetching sassc 2.4.0
10:50:03 AM: Fetching rb-inotify 0.10.1
10:50:03 AM: Fetching em-websocket 0.5.3
10:50:03 AM: Installing rb-inotify 0.10.1
10:50:03 AM: Installing em-websocket 0.5.3
10:50:03 AM: Fetching listen 3.7.1
10:50:03 AM: Installing listen 3.7.1
10:50:03 AM: Installing sassc 2.4.0 with native extensions
10:50:03 AM: Fetching jekyll-watch 2.2.1
10:50:03 AM: Installing jekyll-watch 2.2.1
10:52:15 AM: Fetching jekyll-sass-converter 2.2.0
10:52:15 AM: Installing jekyll-sass-converter 2.2.0
10:52:15 AM: Fetching jekyll 4.3.1
10:52:15 AM: Installing jekyll 4.3.1
10:52:15 AM: Fetching jekyll-github-metadata 2.15.0
10:52:15 AM: Fetching jekyll-include-cache 0.2.1
10:52:15 AM: Fetching jekyll-redirect-from 0.16.0
10:52:15 AM: Fetching jekyll-relative-links 0.6.1
10:52:15 AM: Fetching jekyll-remote-theme 0.4.3
10:52:15 AM: Fetching jekyll-seo-tag 2.8.0
10:52:15 AM: Fetching wai-website-plugin 0.2
10:52:15 AM: Fetching jekyll-sitemap 1.4.0
10:52:15 AM: Installing jekyll-include-cache 0.2.1
10:52:15 AM: Installing wai-website-plugin 0.2
10:52:15 AM: Installing jekyll-relative-links 0.6.1
10:52:15 AM: Installing jekyll-redirect-from 0.16.0
10:52:15 AM: Installing jekyll-seo-tag 2.8.0
10:52:15 AM: Installing jekyll-remote-theme 0.4.3
10:52:15 AM: Installing jekyll-github-metadata 2.15.0
10:52:15 AM: Installing jekyll-sitemap 1.4.0
10:52:15 AM: Using wai-gems 1.0.0 from source at `_external/data/wai-gems`
10:52:15 AM: Bundle complete! 1 Gemfile dependency, 45 gems now installed.
10:52:15 AM: Bundled gems are installed into `/opt/build/cache/bundle`
10:52:15 AM: Post-install message from rubyzip:
10:52:15 AM: RubyZip 3.0 is coming!
10:52:15 AM: **********************
10:52:15 AM: The public API of some Rubyzip classes has been modernized to use named
10:52:15 AM: parameters for optional arguments. Please check your usage of the
10:52:15 AM: following classes:
10:52:15 AM:   * `Zip::File`
10:52:15 AM:   * `Zip::Entry`
10:52:15 AM:   * `Zip::InputStream`
10:52:15 AM:   * `Zip::OutputStream`
10:52:15 AM: Please ensure that your Gemfiles and .gemspecs are suitably restrictive
10:52:15 AM: to avoid an unexpected breakage when 3.0 is released (e.g. ~> 2.3.0).
10:52:15 AM: See https://github.com/rubyzip/rubyzip for details. The Changelog also
10:52:15 AM: lists other enhancements and bugfixes that have been implemented since
10:52:15 AM: version 2.3.0.
10:52:15 AM: Gem bundle installed
10:52:15 AM: Started restoring cached go cache
10:52:15 AM: Finished restoring cached go cache
10:52:17 AM: go version go1.19.13 linux/amd64
10:52:17 AM: Using PHP version 8.0
10:52:18 AM: Downloading and installing node v16.20.2...
10:52:18 AM: Downloading https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz...
10:52:18 AM: Computing checksum with sha256sum
10:52:18 AM: Checksums matched!
10:52:20 AM: Now using node v16.20.2 (npm v8.19.4)
10:52:20 AM: Enabling Node.js Corepack
10:52:20 AM: Started restoring cached build plugins
10:52:20 AM: Finished restoring cached build plugins
10:52:21 AM: Successfully installed dependencies
10:52:21 AM: Starting build script
10:52:21 AM: Detected 1 framework(s)
10:52:21 AM: "jekyll" at version "unknown"
10:52:21 AM: Section completed: initializing
10:52:23 AM: ​
10:52:23 AM: Netlify Build                                                 
10:52:23 AM: ────────────────────────────────────────────────────────────────
10:52:23 AM: ​
10:52:23 AM: ❯ Version
10:52:23 AM:   @netlify/build 29.36.0
10:52:23 AM: ​
10:52:23 AM: ❯ Flags
10:52:23 AM:   baseRelDir: true
10:52:23 AM:   buildId: 65dd5bb1443cef0007d82dec
10:52:23 AM:   deployId: 65dd5bb1443cef0007d82dee
10:52:23 AM: ​
10:52:23 AM: ❯ Current directory
10:52:23 AM:   /opt/build/repo
10:52:23 AM: ​
10:52:23 AM: ❯ Config file
10:52:23 AM:   /opt/build/repo/netlify.toml
10:52:23 AM: ​
10:52:23 AM: ❯ Context
10:52:23 AM:   deploy-preview
10:52:23 AM: ​
10:52:23 AM: build.command from netlify.toml                               
10:52:23 AM: ────────────────────────────────────────────────────────────────
10:52:23 AM: ​
10:52:23 AM: $ git submodule update --init --remote && bundle exec jekyll build --config "_config.yml,_config_staging.yml"
10:52:23 AM: Submodule path "_external/data": checked out "9ca7226375cd053703753a8b9bc0a3ebfc1524a3"
10:52:23 AM: Configuration file: /opt/build/repo/_config.yml
10:52:23 AM: Configuration file: /opt/build/repo/_config_staging.yml
10:52:23 AM:             Source: /opt/build/repo
10:52:23 AM:        Destination: /opt/build/repo/_site
10:52:23 AM:  Incremental build: disabled. Enable with --incremental
10:52:23 AM:       Generating...
10:52:23 AM:       Remote Theme: Using theme w3c/wai-website-theme
10:52:24 AM: WARNING: skipped symlink "/tmp/jekyll-remote-theme-20240227-8215-3gl58x/_data/lang.json".
10:52:24 AM: WARNING: skipped symlink "/tmp/jekyll-remote-theme-20240227-8215-3gl58x/_data/techniques.yml".
10:52:24 AM: WARNING: skipped symlink "/tmp/jekyll-remote-theme-20240227-8215-3gl58x/_data/translations.yml".
10:52:24 AM: WARNING: skipped symlink "/tmp/jekyll-remote-theme-20240227-8215-3gl58x/_data/video-metadata.yml".
10:52:24 AM: WARNING: skipped symlink "/tmp/jekyll-remote-theme-20240227-8215-3gl58x/_data/wcag.yml".
10:52:24 AM: WARNING: skipped symlink "/tmp/jekyll-remote-theme-20240227-8215-3gl58x/wai-videos".
10:52:25 AM: Starting post processing
10:52:25 AM: Skipping form detection
10:52:25 AM: Post processing - header rules
10:52:25 AM: Post processing - redirect rules
10:52:25 AM: Post processing done
10:52:25 AM: Section completed: postprocessing
10:52:25 AM:                     done in 1.472 seconds.
10:52:25 AM:  Auto-regeneration: disabled. Use --watch to enable.
10:52:25 AM: ​
10:52:25 AM: (build.command completed in 2.1s)
10:52:25 AM: ​
10:52:25 AM: Deploy site                                                   
10:52:25 AM: ────────────────────────────────────────────────────────────────
10:52:25 AM: ​
10:52:25 AM: Starting to deploy site from "_site"
10:52:25 AM: Calculating files to upload
10:52:25 AM: 20 new files to upload
10:52:25 AM: 0 new functions to upload
10:52:25 AM: Section completed: deploying
10:52:25 AM: Site deploy was successfully initiated
10:52:25 AM: ​
10:52:25 AM: (Deploy site completed in 318ms)
10:52:25 AM: ​
10:52:25 AM: Netlify Build Complete                                        
10:52:25 AM: ────────────────────────────────────────────────────────────────
10:52:25 AM: ​
10:52:25 AM: (Netlify Build completed in 2.4s)
10:52:26 AM: Site is live ✨
10:52:26 AM: Caching artifacts
10:52:26 AM: Started saving ruby gems
10:52:26 AM: Finished saving ruby gems
10:52:26 AM: Started saving build plugins
10:52:26 AM: Finished saving build plugins
10:52:26 AM: Started saving pip cache
10:52:26 AM: Finished saving pip cache
10:52:26 AM: Started saving emacs cask dependencies
10:52:26 AM: Finished saving emacs cask dependencies
10:52:26 AM: Started saving maven dependencies
10:52:26 AM: Finished saving maven dependencies
10:52:26 AM: Started saving boot dependencies
10:52:26 AM: Finished saving boot dependencies
10:52:26 AM: Started saving rust rustup cache
10:52:26 AM: Finished saving rust rustup cache
10:52:26 AM: Started saving go dependencies
10:52:26 AM: Finished saving go dependencies
10:52:49 AM: Cached Ruby version 2.6.2
10:52:49 AM: Build script success
10:52:49 AM: Section completed: building
10:52:50 AM: Uploading Cache of size 164.1MB
10:52:51 AM: Section completed: cleanup
10:52:51 AM: Finished processing build request in 3m32.411s

**Closed** 2024-03-29 21:38 UTC
