### ISSUE TITLE
ShowTitleBar hides title but space is still being occupied

### ISSUE THREAD

**Issue by remiX-** [MahApps/MahApps.Metro#3206] opened 2018-03-17 17:10 UTC
Hey, so this is had me for the past day until I finally figured out the issue was from upgrading to 1.6.0+

It works fine on 1.5.0
![v1 5 0](https://user-images.githubusercontent.com/2831747/37558058-c516d808-2a16-11e8-9f10-6007386e262e.png)

But not on 1.6.0/1
![v1 6 1](https://user-images.githubusercontent.com/2831747/37558059-cb75a314-2a16-11e8-860d-dc49b4f57599.png)

The text should be centered vertically in both those images. The only difference between the two are the versions used.

**Comment by Pekshev** [comment] 2018-03-19 07:33
It's the same issue - https://github.com/MahApps/MahApps.Metro/issues/3192

**Comment by punker76** [comment] 2018-03-19 07:37
Duplicate of #3192

**Closed by punker76** 2018-03-19 07:37 UTC
Labels: Duplicate
