### ISSUE TITLE
Validation template bug in flyout

### ISSUE THREAD

**Issue by relseah** [MahApps/MahApps.Metro#2779] opened 2016-12-24 20:38 UTC
## What steps will reproduce this issue?

The flyout contains multiple textboxes with attached validation. If the flyout opens the validation template will be instantly shown and not after the first invalid input. Also the message is display on the other side of the screen. After an invalid input with open flyout everything works normal again. 

### Environment

- MahApps.Metro __v1.4.0__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.5__
### Screenshot
![flyout_bug](https://cloud.githubusercontent.com/assets/17870117/21468697/370040b4-ca21-11e6-9122-eac9103dac33.PNG)

**Comment by punker76** [comment] 2020-05-10 21:45
Duplicate of #2695

**Closed by punker76** 2020-05-10 21:45 UTC
Labels: Bug
