### ISSUE TITLE
MetroWindow does not load properly when executed from a non WPF application

### ISSUE THREAD

**Issue by EyalYasovsky** [MahApps/MahApps.Metro#2248] opened 2015-12-03 15:31 UTC
I am trying to launch a MetroWindow from a Console application.
I'm doing it with a thread:
Thread t = new Thread(new ThreadStart(() =>
            {
                MainWindow ui = new MainWindow();
                
                ui.Show();
                System.Windows.Threading.Dispatcher.Run();

            }
            ));
            t.SetApartmentState(ApartmentState.STA);
            t.IsBackground = false;
            t.Start();  
The window loads but not everything is as expected, The title bar is black and the button does not got the Metro style.
![loadasdll](https://cloud.githubusercontent.com/assets/15193919/11564642/ef072ca6-99e2-11e5-9bc5-dc015d5a8698.png)

When I am executing the application directly from the WPF project everything looks good:

![loadasexe](https://cloud.githubusercontent.com/assets/15193919/11564705/3b17026a-99e3-11e5-939d-522a6bf5fb92.jpg)

I am developing with Visual Studio 2015
my OS is Win7
MahApps.Metro.dll version is 1.1.3.223
The issue is reproducible as I described.
Thanks,
Eyal

**Comment by xxMUROxx** [comment] 2015-12-04 14:52
I think the problem is because if you create a MetroWindow from Console, or any non WPF project the resources meeded from MahApps are not loaded. Therefore you need to be sure that you load the resources that are least needed

~~~csharp
var d= new ResourceDictionary();
d.Source = new Uri("URI-TO-RESOURCE", UriKind.Relative); 
Application.Current.Resources.MergedDictionaries.Add(d);
~~~

The resources needed are listed there: https://github.com/MahApps/MahApps.Metro#a-short-how-to

**Comment by EyalYasovsky** [comment] 2015-12-06 06:49
Thanks, you saved the day !!!
I was so desperate I started to implement my UI in a separated process :)
You saved me some time and headaches.

**Closed** 2015-12-06 07:41 UTC
