### ISSUE TITLE
Glowborder does not disappear cleanly when running in 64 bit.

### ISSUE THREAD

**Issue by rojasc** [MahApps/MahApps.Metro#2084] opened 2015-08-20 17:55 UTC
If your platform target is x64 or if you use "Any CPU" without "Prefer 32-bin" checked on a 64 bit machine, when closing a window with glow, the glow will not disappear cleanly. It seems disappear edge by edge and it will remain visible after the window disappears for about a second.

**Comment by punker76** [comment] 2015-08-26 09:46
@rojasc with which MahApps version are you get this issue? i don't see such issue with my machines™.

**Comment by rojasc** [comment] 2015-08-26 13:35
I'm using 1.1.2 also, if it matters running on Win8.1. If you would like, I could provide some screen captures or a video.

**Comment by punker76** [comment] 2015-08-26 13:44
@rojasc can you try the latest alpha from nuget?

**Comment by rojasc** [comment] 2015-08-26 13:46
Just tried and no change in behavior. I'm installing a screen recorder right now so you can see what is happening.

**Comment by rojasc** [comment] 2015-08-26 14:13
Here is a video of the issue in my app: https://youtu.be/TLN4ZQ_rgfo
Here is a video of it happening in the demo app: https://youtu.be/ha1fF68cAFo

**Comment by punker76** [comment] 2015-08-27 07:18
@rojasc i can't reproduce this with the settings and the latest source on my machine™ with win 10 64 bit professional...

**Comment by rojasc** [comment] 2015-08-27 13:03
I'm using Win8.1 Enterprise. Do you believe its something to do with the library? or something actually with the OS or a video driver? I just find it very strange that it only happens when I build it for x64.

**Comment by rojasc** [comment] 2015-08-27 14:00
I also just noticed that it does not happen on a Release build.

**Comment by punker76** [comment] 2015-08-30 18:49
@rojasc so this is only happen with attached debugger? if so, then i will close this issue.

**Comment by rojasc** [comment] 2015-09-02 13:27
It only happens when built in Debug mode. It still happens if its a Debug build and the debugger is not attached. It only doesn't happen on Release builds.

**Comment by moser96** [comment] 2015-09-12 08:54
I'm also faced the same issue. As @rojasc said it only doesn't happen on Release builds.
I'm using Windows 10 Home.

**Comment by punker76** [comment] 2015-10-01 19:58
@rojasc can you test your app with the latest alpha (>=181)? thx for the effort!

**Closed** 2015-10-23 22:16 UTC
Labels: help wanted, Jump In
