### ISSUE TITLE
SplitView  doesn't work with Caliburn.Micro ActivateItem(xxx)

### ISSUE THREAD

**Issue by waleswood** [MahApps/MahApps.Metro#3104] opened 2017-11-17 08:33 UTC
## What steps will reproduce this issue?
``` XAML
<controls:SplitView Grid.Row="1" DisplayMode="Overlay" IsPaneOpen="{Binding ElementName=Hamburger, Path=IsChecked, Mode=OneWay}" PanePlacement="Right">
    <controls:SplitView.Pane>
        <StackPanel>
        </StackPanel>
        </controls:SplitView.Pane>
            <ContentControl x:Name="ActiveItem" />
        </controls:SplitView>
```
``` C#
public void ShowPatientMgt()
{
    ActivateItem(new demoViewModel);
}
```
like this,

![image](https://user-images.githubusercontent.com/3008502/32937375-30b614ec-cbb3-11e7-9ad0-287d6f6d3d7f.png)

### Expected outcome
Did not show anything

### Environment

- MahApps.Metro __v1.5.0__
- Windows OS __10__
- Visual Studio __2017__
- .NET Framework __4.0__

**Comment by punker76** [comment] 2017-11-17 08:40
Duplicate of #3089

**Closed** 2018-01-14 11:43 UTC
