### ISSUE TITLE
TabControl is always the last one to receive focus when using Tab key navigation

### ISSUE THREAD

**Issue by shinywong** [MahApps/MahApps.Metro#3765] opened 2020-03-21 16:26 UTC
**Describe the bug**
TabControl is always the last one to receive Tab focus, no matter where it was placed in the XAML file, and no matter which value its TabIndex was set.

**To Reproduce**
1. XAML file snippet:
```xaml
<StackPanel>
    <StackPanel>
        <Button Content="Button A"/>
        <TabControl>
            <TabItem Header="Tab">
                <Button Content="Button B"/>
            </TabItem>
        </TabControl>
    </StackPanel>
    <Button Content="Button C"/>
</StackPanel>
```
2. Navigate using Tab key, you will find out the actual Tab order is
   "Button A" -> "Button C" -> "Button B".

**Expected behavior**
The Tab order should be "Button A" -> "Button B" -> "Button C".
Without using MahApps.Metro, it will work as expected.

**Screenshots**
(None)

**Environment**
 - MahApps.Metro: v1.6.5
 - OS: Win10 1909
 - Visual Studio: 2019 16.5.0
 - .NET Framework: 4.8

**Repo**
(None)

**Additional context**
(None)

**Comment by punker76** [comment] 2020-05-19 22:37
@shinywong I can't reproduce this with the current source. So I'll close this for now. But feel free to re-open this, if you are still get this issue with the latest version.

**Closed by punker76** 2020-05-19 22:37 UTC
Labels: Bug
