### ISSUE TITLE
DataGrid binding error when scrolled horizontally

### ISSUE THREAD

**Issue by fpawel** [MahApps/MahApps.Metro#2213] opened 2015-11-17 08:18 UTC
Subject:

```
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='-0.419463087248322' BindingExpression:Path=CellsPanelHorizontalOffset; DataItem='DataGrid' (Name='DataGridProductsValues'); target element is 'Button' (Name=''); target property is 'Width' (type 'Double')
```

The error occurs when HeadersVisibility="Column", and does not when HeadersVisibility="All". 
I think the problem is in Controls.DataGrid.xaml in 

```
<Button Command="{x:Static DataGrid.SelectAllCommand}"
                                                Focusable="false"
                                                Style="{DynamicResource {ComponentResourceKey ResourceId=MetroDataGridSelectAllButtonStyle, TypeInTargetAssembly={x:Type DataGrid}}}"
                                                Visibility="{Binding HeadersVisibility, ConverterParameter={x:Static DataGridHeadersVisibility.All}, Converter={x:Static DataGrid.HeadersVisibilityConverter}, RelativeSource={RelativeSource AncestorType={x:Type DataGrid}}}"
                                                Width="{Binding CellsPanelHorizontalOffset, RelativeSource={RelativeSource AncestorType={x:Type DataGrid}}}" />
```

**Comment by punker76** [comment] 2016-12-07 16:01
@fpawel I close this for now, cause I can't reproduce this with the current source. If it's raising again, please add a short application (or put it on Github). Thx.

**Closed by punker76** 2016-12-07 16:01 UTC
