### ISSUE TITLE
Auto complete text box

### ISSUE THREAD

**Issue by BlythMeister** [MahApps/MahApps.Metro#2993] opened 2017-06-23 05:11 UTC
I would really like to include an auto complete text box in my app similar to how https://wpfautocomplete.codeplex.com works.
But I'm not sure how to get that example of auto complete to have all the mahapps styling.

Essentially, a text box which can provide suggestions based on entered data is what I am after 🙂

**Comment by fredericoregateiro** [comment] 2017-06-30 12:34
+1

**Comment by punker76** [comment] 2018-01-20 23:37
Duplicate of #2625

**Closed by punker76** 2018-01-20 23:37 UTC
Labels: duplicate
