### ISSUE TITLE
Exception when TopMost is set in a child window

### ISSUE THREAD

**Issue by zerodev1200** [MahApps/MahApps.Metro#4255] opened 2022-01-23 15:30 UTC
## Describe the bug
If the child window is set to TopMost and the main window is closed with the child window open, an exception is raised.

## Steps to reproduce

1.Open the main window and press [OpenChildWindow].
2.main window active and close it.
3.An exception will occur.
[https://github.com/zerodev1200/MetroTopMostIssueSample](https://github.com/zerodev1200/MetroTopMostIssueSample)

Tip: If you delete Topmost="True" in SubWindow.xaml(child window), the exception will not occur.

## Expected behavior

The window should close without raising an exception.
## Actual behavior

System.ArgumentException: 'E_INVALIDARG'
## Environment

```
MahApps.Metro version: v2.4.9
Windows build number: Win10 21H2
Visual Studio: 2022 17.0.5
Target Framework: .Net 6 
```

## Screenshots

![MetroException](https://user-images.githubusercontent.com/42404360/150685577-6c1d1f98-b38e-4a0c-94d6-f6a0cf689aa9.jpg)

**Comment by batzen** [comment] 2022-04-17 16:50
Can't reproduce this on Windows 11.
Could you attach the full stacktrace?
Or try the MahApps.Metro version from https://github.com/batzen/MahApps.Metro/tree/features/ControlzEx6 that version uses the next ControlzEx version 6.0 which should not expose that kind of issues. At least we hope so.

**Comment by punker76** [comment] 2023-02-05 14:03
This is fixed in latest source with latest ControlzEx pre version.

**Closed by punker76** 2023-02-05 14:03 UTC
Labels: Bug
