### ISSUE TITLE
[Suggestion] WPF ToolBar - Detect when item is set into ToolBarOverflowPanel

### ISSUE THREAD

**Issue by Evangelink** [MahApps/MahApps.Metro#2652] opened 2016-09-15 13:41 UTC
I wrote a couple of month ago a little helper that can be used on a toolbar item to detect if it is currently displayed or in overflow. The idea was to be able to change the style of the item depending on whether or not it is displayed to reproduce the Windows 10 toolbar (Mail app...).

More info can be found here: http://stackoverflow.com/questions/36328280/wpf-toolbar-detect-when-item-is-set-into-toolbaroverflowpanel

I was wondering if this could be something interesting to incorporate to MahApps? If agreed I will make a PR with a little style example.

Cheers

**Comment by Evangelink** [comment] 2016-09-20 12:08
Will do the PR as soon as I understand how to commit without having my commit automatically added to the SplitView PR.... *git noob inside*

**Comment by punker76** [comment] 2016-09-20 12:13
@Evangelink The problem is that you directly work on the develop branch. You should always create your own branch forked from the develop branch to work on a new feature or fixed issue. You can then make a PR from this branch and still working on it without changeing the other PRs.

**Comment by Evangelink** [comment] 2016-09-20 12:33
@punker76 Ok. Can I undo my PR to recreate it through some branch? Also do you mean 1 branch per fix/feature or just one dev branch and all commits on it?

**Comment by punker76** [comment] 2016-09-20 12:35
@Evangelink Always One branch from `develop` branch per fix/feature. Maybe you close your current PRs and create new one...

**Comment by punker76** [comment] 2019-05-20 12:12
I get the same result, if I use the `ToolBar.IsOverflowItem` property, so I’m closing for now this PR.

Please let me know if you still need this extra property.

Thank you! 🙏

**Closed by punker76** 2019-05-20 12:12 UTC
Labels: Feature Request
