### ISSUE TITLE
TransitioningContentControl ignores the ContentTemplateSelector

### ISSUE THREAD

**Issue by WillSullivan** [MahApps/MahApps.Metro#2533] opened 2016-06-03 18:30 UTC
I've got a view model support type that wraps my models.  In order to locate the correct template for the model, I have a custom content template selector that finds the correct template based on the wrapped model.  Works fine in any other content control, but the TCC does not use the configured selector to find the correct data template. 

--
### Environment

- MahApps.Metro 1.2.4
- Windows 10
- Visual Studio 2015
- .NET Framework 4.6.1

**Comment by punker76** [comment] 2016-06-04 20:10
@WillSullivan Can you just try make a short reproducable app? Thx!

**Comment by punker76** [comment] 2016-06-09 21:22
@WillSullivan I can't reproduce this with the latest pre-release. I close this for now, feel free to re-open this issue if you have still problems with it.

**Closed by punker76** 2016-06-09 21:22 UTC
