### ISSUE TITLE
MetroWindow fails to display on some machines

### ISSUE THREAD

**Issue by DingpingZhang** [MahApps/MahApps.Metro#3749] opened 2020-02-21 09:41 UTC
**Describe the bug**

On some machines, the `<MetroWindow />` will not be rendered normally. You will only see one glow border, and the content in the middle will be transparent (but mouse clicks are not allowed).

![unnamed](https://user-images.githubusercontent.com/8541016/75022107-74ef6c00-54d0-11ea-9293-274e69a6ef51.png)

**To Reproduce**

The problem was on the user's machine and I couldn't reproduce it myself. The demo exe I use is just a new wpf project, then change the `<Window />` to `<MetroWindow />` on the `MainWindow.xaml` file, and add related resources in `App.xaml`. 

Prior to the introduction of `<MetroWindow />`, original wpf windows worked fine on the user's mechine.

I have no clue on this issue. Can you provide some ideas?

**Comment by NeomMob** [comment] 2020-02-21 09:55
Try to set `System.Windows.Media.RenderOptions.ProcessRenderMode = RenderMode.SoftwareOnly;` before showing your window.

**Comment by timunie** [comment] 2020-02-21 10:27
Hi @DingpingZhang ,
can you provide more information about the environment? At least MahApps version and the OS of the machine with the problem.

Thanks,
Tim

**Comment by DingpingZhang** [comment] 2020-02-22 03:33
@timunie 

I am soory I forgot.

1. MahApps version: `v1.6.5`
2. OS: `win10`
3. NetFx >= 4.7.1

**Comment by punker76** [comment] 2020-02-22 11:19
@DingpingZhang This is maybe fixed in current source. You can try to use the latest pre-release (also available on NuGet).

**Comment by DingpingZhang** [comment] 2020-02-22 12:56
Hi @punker76 Could you tell me the reason for this issue?

**Comment by punker76** [comment] 2020-02-22 13:05
@DingpingZhang I can’t give you an exact answer. But we changed more then one thing in our window chrome to fix some WPF bugs. Another one can be a corrupt video driver. I don’t know.

**Comment by punker76** [comment] 2020-04-15 20:09
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏

**Closed by punker76** 2020-04-15 20:09 UTC
