### ISSUE TITLE
MetroWindow acts as though Topmost is enabled until disabled while running

### ISSUE THREAD

**Issue by EricLauber** [MahApps/MahApps.Metro#3787] opened 2020-05-01 20:11 UTC
**Describe the bug**
All of the `MetroWindow` objects in my application are acting as though I've set `Topmost = true` when I haven't. Explicitly configuring `Topmost = false` in XAML or as part of a DataContext does not change this - but copying the logic from `MenuItem` logic from the most recent `develop` branch example **does** fix it.

**To Reproduce**
1. Create new .NET Core 3.1 WPF project in Visual Studio.
2. Add latest prerelease NuGet for MahApps.
3. Change default `MainWindow` to leverage `MahApps.Metro` namespace and to inherit `MetroWindow` instead of `Window`.
4. Add the following to `App.xaml`:
```
<ResourceDictionary.MergedDictionaries>
    <!-- MahApps -->
<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/FlatButton.xaml" />
</ResourceDictionary.MergedDictionaries>
```
5. Run the application and find that the window is always `Topmost`, system-wide.
6. Stop application. Add an object like a `ToggleSwitch` and tie the `IsOn` attribute as follows:
`IsOn="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type MahAppsControls:MetroWindow}}, Path=Topmost}" `
7. Restart application. Find that although the `ToggleSwitch` is `false`, the window is `Topmost`. Enable the `ToggleSwitch`, and then disable it. The window is now nolonger `Topmost`

I have found you can replace the last steps with the Visual Studio debugger by viewing the properties of the `MetroWindow`. If I forcefully enable `Topmost` and then disable it, the window well then act as though `Topmost` is disabled.

I have also found this occurs for not just my `MainWindow` but any other `MetroWindow` I add to the application.

**Expected behavior**
I expect `MetroWindow` objects to default to `Topmost = false`, and I expect that if I explicitly configure this in the XAML that the `MetroWindow` will respond to this configuration.

**Environment:**
 - MahApps.Metro 2.0.0-alpha0775
 - OS: Windows 10 Pro 1909 18363.778
 - Visual Studio 2019 16.4.3
 - .NET Core 3.1

**Comment by punker76** [comment] 2020-05-01 20:29
@EricLauber Can you try this simple app https://github.com/punker76/MahApps.Metro.netcoreapp30 ? I have the same specs and can't reproduce this issue. Thx.

**Comment by punker76** [comment] 2020-05-01 20:31
@EricLauber My specs

```
dotnet --version
3.1.201

Windows 10 Pro 1909 18363.778
```

**Comment by EricLauber** [comment] 2020-05-01 20:38
I hadn't checked my .NET version, I'm on `3.1.101`.
I cloned that app and it worked fine. The MahApps sample also had worked.

**Comment by EricLauber** [comment] 2020-05-01 20:48
Is there something I could enable or be looking for in console output to see if some other portion of my application is interacting with MahApps and contributing to the issue?

**Comment by punker76** [comment] 2020-05-01 20:55
@EricLauber Can you put your sample here on GitHub? It seems curious that your sample doesn't work but the main demo and my one.

**Comment by EricLauber** [comment] 2020-05-01 21:09
I'm working on a business application and cannot share much of the code. I will remove the business logic and see what I can upload. It probably won't be today.

**Comment by punker76** [comment] 2020-05-01 21:14
@EricLauber You can try to use this code inside your window. Maybe it helps to see if the TopMost is set on sart.

```
using ControlzEx;

private PropertyChangeNotifier topMostChangeNotifier;

public TestWindow()
{
    this.topMostChangeNotifier = new PropertyChangeNotifier(this.AssociatedObject, Window.TopmostProperty);
    this.topMostChangeNotifier.ValueChanged += this.TopMostChangeNotifierOnValueChanged;
}

private void TopMostChangeNotifierOnValueChanged(object sender, EventArgs e)
{
}
```

**Comment by EricLauber** [comment] 2020-05-01 21:21
I placed `TestWindow` contents in the constructor **underneath** `InitializeComponent`. It did not fire with instantiating or showing the window, and it did not fire when I did the maximize/minimize actions. If I actually modified the property (such as through Visual Studio) the event would fire two or three times.

**Comment by punker76** [comment] 2020-05-01 21:34
@EricLauber Can you say which version of ControlzEx you have referenced?

**Comment by EricLauber** [comment] 2020-05-01 22:45
It's 4.3.0-alpha0085
Okay. Thank you for the help - I have found my issue. It has nothing to do with MahApps. I began removing code to prepare to upload a copy and upon removing a section I believed to be unrelated, the `Topmost` behavior began working correctly. I'm not sure why this is, but it's clearly something I did and not part of the library.

Do you have any special procedure for closing issues or otherwise removing them?

**Comment by batzen** [comment] 2020-05-02 06:32
Could you tell us what that code did? Maybe it's still something we can prevent or at least add to a list.

**Comment by EricLauber** [comment] 2020-05-02 15:40
My WPF application overrides `OnStartup` in order to display our own customer splash screen (this is a `Window`). While the splash screen is up, we load database information. When everything is complete, we:
1.  Instantiate a `MetroWindow` that is our `MainWindow`
1.  Set the `Owner` of the `MetroWindow` to the splash screen `Window`. Our `MetroWindow` is configured with `WindowStartupLocation="CenterOwner"` - this provides some user experience consistency with the `MetroWindow` appearing on the same monitor and directly behind the splash screen.
1.   Use `MetroWindow.Show()` to display it in a non-modal way. Now that it is centered behind the splash screen, we change its `Owner` to `null`.
1.  Do some final object-cleanup and and call `.Close()` on the splash screen.

As soon as I removed configuring the `Owner` of the `MetroWindow` to the splash screen (just comment that line out), the weird `Topmost` issue went away.

**Comment by batzen** [comment] 2020-05-03 06:42
That's interesting as normally your window should get closed when you close it's owner.
Having a topmost owner seems to break this behavior.
May i say that making a splash screen topmost is not nice application behavior? It always annoys me when applications do that 😉

**Closed** 2020-05-06 17:03 UTC
