### ISSUE TITLE
MetroCircleButtonStyle IsEnabled no effect

### ISSUE THREAD

**Issue by forgacsbert** [MahApps/MahApps.Metro#3098] opened 2017-11-06 10:15 UTC
When adding a button with the style MetroCircleButtonStyle, the IsEnabled property doesn't change the appearance of the button (it only can't be pressed), see code:

```
<Button Width="50"
 Height="50"
 BorderThickness="0"
 Background="{StaticResource WordGreenBrush}"
 Foreground="{StaticResource ForegroundLightBrush}" 
 Style="{StaticResource MetroCircleButtonStyle}"
 Content = "T"
 IsEnabled="False"/>
```

**Comment by punker76** [comment] 2017-11-10 14:12
Duplicate of #3101

**Closed by punker76** 2017-11-10 14:12 UTC
