### ISSUE TITLE
Odd HamburgerMenu padding/margin

### ISSUE THREAD

**Issue by Nuklon** [MahApps/MahApps.Metro#3300] opened 2018-08-07 16:22 UTC
**Describe the bug**
Since a while the padding/margin of the hamburger menu isn't the same anymore as previous versions.

This is happening at the top (as shown in the screenshot), as well as at the bottom of the hamburgermenu.

**Expected behavior**
Have the menu items lined up correctly again.

**Screenshots**
![img](https://i.imgur.com/Wf6Ej1K.png)

**Environment(please complete the following information):**
 - MahApps.Metro version: last NuGet
 - OS: Win 10

**Repo**
Same issue happens in the MahApps Demo app (both directly below hamburger icon and at the last item).

**Comment by punker76** [comment] 2018-09-04 12:02
Duplicate of #3284

**Closed by punker76** 2018-09-04 12:02 UTC
Labels: Bug
