### ISSUE TITLE
MetroNavigationWindow cannot be used

### ISSUE THREAD

**Issue by MrMitch** [MahApps/MahApps.Metro#1837] opened 2015-03-12 17:07 UTC
I'm trying to use a MetroNavigationWindow but the app won't compile, giving me the following error : 
`MC6017: MahApps.Metro.Controls.MetroNavigationWindow cannot be root of a XAML file because it was defined using XAML.`

The simplest example to reproduce is the following, in the MainWindow.xaml file : 

```xaml
<NavigationWindow x:Class="BugMetroWindow.MainWindow"
                  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                  xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
                  Title="MainWindow" Height="350" Width="525" 
                  Source="HomePage.xaml"/>

```

**Comment by flagbug** [comment] 2015-03-12 17:09
Duplicate of https://github.com/MahApps/MahApps.Metro/issues/1828

**Closed by flagbug** 2015-03-12 17:09 UTC

**Comment by MrMitch** [comment] 2015-03-13 08:05
thank you
