### ISSUE TITLE
Can't find resource mahapps.styles.button.flat

### ISSUE THREAD

**Issue by Mager66** [MahApps/MahApps.Metro#4046] opened 2021-02-17 11:53 UTC
Hi, I am developing an app as a CAD extension. My view are called by a classlibrary and I am getting trouble as soon as I use some button control saying "can't find resource mahapps.styles.button.flat".

My view app loos like this:

```xaml
<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.Buttons.xaml" />
                <!--<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.FlatButton.xaml" />-->
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.FlatButton.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
```

My test window looks like this:

```xaml
<mah:MetroWindow x:Class="ELPROCADTestWPFView.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mah="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"  
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:ELPROCADTestWPFView"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    
    <Grid>
        <mah:SplitButton Width="100" Height="100"
                         Foreground="Red"/>
                <Button Style="{StaticResource MahApps.Styles.Button.Flat}"
                        Width="50" Height="50"
                        Foreground="Red"/>
            </Grid>
</mah:MetroWindow>
```

Also my classlib is referencing Mahapps.Metro....

When running just the MetroWindow without any button controls it works just fine.

Best Regards
Magnus Eriksson

**Comment by punker76** [comment] 2021-02-17 12:02
@Mager66 Hi Magnus, to use the flat Button style you don't need to add the Buttons or FlatButton resources. Normaly this should work:

```xaml
<Application x:Class="SampleApp"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             StartupUri="MainWindow.xaml">
  <Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <!-- MahApps.Metro resource dictionaries. Make sure that all file names are Case Sensitive! -->
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
        <!-- Theme setting -->
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </Application.Resources>
</Application>
```

https://mahapps.com/docs/guides/quick-start#mahapps-build-in-styles-and-themes

It could be that you don't have an App, if so then you must add the resources to every Window of your extension.

Another trick is to use the DynamicResource instead StaticResource, because the resources will maybe are loaded later.

**Comment by punker76** [comment] 2021-02-27 11:37
@Mager66 I’m closing this for now. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

You can also create a simple app with exactly this one issue and put it on GitHub, in most cases this is the fastest way to see what's going wrong.

Thank you! 🙏

**Closed by punker76** 2021-02-27 11:37 UTC
