### ISSUE TITLE
Can't disable scientific value in NumericUpDown

### ISSUE THREAD

**Issue by Stonex123** [MahApps/MahApps.Metro#2496] opened 2016-05-10 16:32 UTC
I want a NumericUpDown that allow only integer value, actually I'm using the Pre-release and I've disabled the double value with: `HasDecimal = False`, but if I type 5e the NumericUpDown accept the e.
I want disable this features, how can I do that? Thanks in advance.

**Comment by punker76** [comment] 2018-01-17 14:41
Duplicate of #2422

**Closed by punker76** 2018-01-17 14:41 UTC
Labels: duplicate
